name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - development
      - staging
      - canary
  pull_request:

jobs:
  # Build and Test Job
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [backend, frontend, ml-service]
    steps:
      # Checkout the code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Build and Test the Service
      - name: Build and Test Service
        run: npx nx run ${{ matrix.service }}:build --parallel

      # Run Tests
      - name: Run Tests
        run: npx nx run ${{ matrix.service }}:test

      # Static Analysis and Security Scanning
      - name: Static Analysis and Security Scan
        run: |
          npx nx run ${{ matrix.service }}:lint
          if [ "${{ matrix.service }}" == "ml-service" ]; then
            pip install pip-audit && pip-audit
          else
            npm audit
          fi

      # Upload Build Artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.service }}-build
          path: dist/${{ matrix.service }}

  # Build and Push Docker Images
  build-and-push-docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build Docker Images Using Nx Target
      - name: Build and Push Docker Images
        run: |
          npx nx run-many --target=docker-build --all

  # Deploy to Kubernetes Based on Branch
  deploy:
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Deployment Environment
        id: set-env
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "env=production" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "staging" ]]; then
            echo "env=staging" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "canary" ]]; then
            echo "env=canary" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "development" ]]; then
            echo "env=development" >> $GITHUB_ENV
          fi

      # # Deploy to Kubernetes
      # - name: Deploy to Kubernetes
      #   run: |
      #     env=$(cat $GITHUB_ENV | grep "env=" | cut -d'=' -f2)
      #     kubectl apply -f deployment/${env}-frontend.yaml
      #     kubectl apply -f deployment/${env}-backend.yaml
      #     kubectl apply -f deployment/${env}-ml-service.yaml
